export default function Head() {
  return (
    <>
      <title>Project Amelia </title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link
        rel="icon"
        href="https://drive.google.com/uc?export=download&id=1O2hZPiggKMtVErg-8AG2zDsk9xNfjlHB"
      />
    </>
  );
}
